### ISSUE TITLE
Howto create a MySQL Cluster config examples and documentation 

### ISSUE THREAD

**Issue by simon-k8s** [grtl/mysql-operator#110]
Hi,

I just deployed the mysql-operator to my kubernetes cluster. That worked fine once i modified the example from the readme to:

`kubectl run mysql-operator --image=grtl/mysql-operator:latest`

Now I have some new crd but how do I configure a MySQL Cluster and a MySQL backup with the operator. I can't find any infos about that. At least an example yaml would be could. If you can push me in the right direction I am willing to offer my help with the documentation. 

Cheers Simon

**Comment by earlgreyz** [comment]
Hi Simon,
I've created a PR adding usage examples to the README https://github.com/grtl/mysql-operator/pull/111

Let me know if this helps.

**Comment by simon-k8s** [comment]
Hi @earlgreyz 

Thank you for the usage doc. I followed the docs and and used the yaml you provided. I started of created the secret then I used this yaml:

`apiVersion: cr.mysqloperator.grtl.github.com/v1
kind: MySQLCluster
metadata:
  name: "cluster"
spec:
  password: "mysql-secret"
  port: "3306"                 # Port on which the service will expose the MySQL
  replicas: "2"                # Number of replicas
  storage: "1Gi"               # Persistance Volume Claim size
  mysqlImage: "mysql:latest"`

The services and the stateful set get created. But the current state stays an 0 pods:

`kubectl get statefulset
NAME         DESIRED   CURRENT   AGE
my-cluster   2         0         9m`

A describe on the stateful set shows this error:

`Warning  FailedCreate  26s (x23 over 4m)  statefulset-controller  create Pod my-cluster-0 in StatefulSet my-cluster failed error: Pod "my-cluster-0" is invalid: [spec.containers[0].env[0].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

Can you offer any help?

**Comment by earlgreyz** [comment]
Sorry instead of `password` the field should be named `secret` according to the latest version of

**Comment by simon-k8s** [comment]
@earlgreyz Thanks I could successfully create a cluster now. I will give the backup and restore options a try next.
